[2023-07-12 00:33:21,740] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2022-08-14T00:00:00+00:00 [queued]>
[2023-07-12 00:33:21,934] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2022-08-14T00:00:00+00:00 [queued]>
[2023-07-12 00:33:21,935] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-12 00:33:21,935] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-07-12 00:33:21,935] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-12 00:33:22,998] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): segunda_tarea> on 2022-08-14 00:00:00+00:00
[2023-07-12 00:33:23,177] {standard_task_runner.py:52} INFO - Started process 268 to run task
[2023-07-12 00:33:23,304] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'segunda_tarea', 'scheduled__2022-08-14T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmpdk_iu14y', '--error-file', '/tmp/tmph2eil6fy']
[2023-07-12 00:33:23,325] {standard_task_runner.py:80} INFO - Job 43: Subtask segunda_tarea
[2023-07-12 00:33:25,202] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2022-08-14T00:00:00+00:00 [running]> on host 7a1b6d75866e
[2023-07-12 00:33:27,089] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag_v3
AIRFLOW_CTX_TASK_ID=segunda_tarea
AIRFLOW_CTX_EXECUTION_DATE=2022-08-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-14T00:00:00+00:00
[2023-07-12 00:33:27,091] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-07-12 00:33:27,091] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hola, soy la tarea 2 y sere corrida luego de la Tarea 1']
[2023-07-12 00:33:27,381] {subprocess.py:85} INFO - Output:
[2023-07-12 00:33:27,454] {subprocess.py:92} INFO - hola, soy la tarea 2 y sere corrida luego de la Tarea 1
[2023-07-12 00:33:27,456] {subprocess.py:96} INFO - Command exited with return code 0
[2023-07-12 00:33:28,332] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=mi_primer_dag_v3, task_id=segunda_tarea, execution_date=20220814T000000, start_date=20230712T003321, end_date=20230712T003328
[2023-07-12 00:33:29,032] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-07-12 00:33:29,155] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 268. PIDs of all processes in the group: [268]
[2023-07-12 00:33:29,155] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 268
[2023-07-12 00:33:29,189] {process_utils.py:75} INFO - Process psutil.Process(pid=268, status='terminated', exitcode=0, started='00:33:22') (268) terminated with exit code 0
