[2023-07-13 21:14:54,932] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.tercera_tarea scheduled__2023-02-07T00:00:00+00:00 [queued]>
[2023-07-13 21:14:55,222] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.tercera_tarea scheduled__2023-02-07T00:00:00+00:00 [queued]>
[2023-07-13 21:14:55,222] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 21:14:55,222] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-07-13 21:14:55,223] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 21:14:55,266] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): tercera_tarea> on 2023-02-07 00:00:00+00:00
[2023-07-13 21:14:55,283] {standard_task_runner.py:52} INFO - Started process 2627 to run task
[2023-07-13 21:14:55,439] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'tercera_tarea', 'scheduled__2023-02-07T00:00:00+00:00', '--job-id', '585', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmpqoswj8p4', '--error-file', '/tmp/tmpvd_8t2wi']
[2023-07-13 21:14:55,440] {standard_task_runner.py:80} INFO - Job 585: Subtask tercera_tarea
[2023-07-13 21:14:56,857] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.tercera_tarea scheduled__2023-02-07T00:00:00+00:00 [running]> on host 7a1b6d75866e
[2023-07-13 21:14:59,671] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ari Feldman
AIRFLOW_CTX_DAG_ID=mi_primer_dag_v3
AIRFLOW_CTX_TASK_ID=tercera_tarea
AIRFLOW_CTX_EXECUTION_DATE=2023-02-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-07T00:00:00+00:00
[2023-07-13 21:14:59,688] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-07-13 21:14:59,689] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hola, soy la tarea 3 y sere corrida luego de Tarea 1 al mismo tiempo que Tarea 2']
[2023-07-13 21:14:59,892] {subprocess.py:85} INFO - Output:
[2023-07-13 21:14:59,914] {subprocess.py:92} INFO - hola, soy la tarea 3 y sere corrida luego de Tarea 1 al mismo tiempo que Tarea 2
[2023-07-13 21:14:59,917] {subprocess.py:96} INFO - Command exited with return code 0
[2023-07-13 21:15:00,760] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=mi_primer_dag_v3, task_id=tercera_tarea, execution_date=20230207T000000, start_date=20230713T211454, end_date=20230713T211500
[2023-07-13 21:15:01,210] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-07-13 21:15:01,232] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 2627. PIDs of all processes in the group: [2627]
[2023-07-13 21:15:01,232] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 2627
[2023-07-13 21:15:01,367] {process_utils.py:75} INFO - Process psutil.Process(pid=2627, status='terminated', exitcode=0, started='21:14:54') (2627) terminated with exit code 0
