[2023-07-13 21:07:48,997] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2022-09-21T00:00:00+00:00 [queued]>
[2023-07-13 21:07:49,303] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2022-09-21T00:00:00+00:00 [queued]>
[2023-07-13 21:07:49,315] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 21:07:49,315] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-07-13 21:07:49,348] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 21:07:49,675] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): segunda_tarea> on 2022-09-21 00:00:00+00:00
[2023-07-13 21:07:49,725] {standard_task_runner.py:52} INFO - Started process 1180 to run task
[2023-07-13 21:07:49,733] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'segunda_tarea', 'scheduled__2022-09-21T00:00:00+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmpno33m7yt', '--error-file', '/tmp/tmpc_gf87gu']
[2023-07-13 21:07:49,734] {standard_task_runner.py:80} INFO - Job 166: Subtask segunda_tarea
[2023-07-13 21:07:51,448] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2022-09-21T00:00:00+00:00 [running]> on host 7a1b6d75866e
[2023-07-13 21:07:53,612] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag_v3
AIRFLOW_CTX_TASK_ID=segunda_tarea
AIRFLOW_CTX_EXECUTION_DATE=2022-09-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-21T00:00:00+00:00
[2023-07-13 21:07:53,631] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-07-13 21:07:53,678] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hola, soy la tarea 2 y sere corrida luego de la Tarea 1']
[2023-07-13 21:07:54,095] {subprocess.py:85} INFO - Output:
[2023-07-13 21:07:54,133] {subprocess.py:92} INFO - hola, soy la tarea 2 y sere corrida luego de la Tarea 1
[2023-07-13 21:07:54,210] {subprocess.py:96} INFO - Command exited with return code 0
[2023-07-13 21:07:55,203] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=mi_primer_dag_v3, task_id=segunda_tarea, execution_date=20220921T000000, start_date=20230713T210749, end_date=20230713T210755
[2023-07-13 21:07:55,734] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-07-13 21:07:55,797] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 1180. PIDs of all processes in the group: [1180]
[2023-07-13 21:07:55,820] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 1180
[2023-07-13 21:07:55,986] {process_utils.py:75} INFO - Process psutil.Process(pid=1180, status='terminated', exitcode=0, started='21:07:48') (1180) terminated with exit code 0
