[2023-08-02 00:00:01,195] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_api_marvel.extract scheduled__2023-08-01T00:00:00+00:00 [queued]>
[2023-08-02 00:00:01,209] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_api_marvel.extract scheduled__2023-08-01T00:00:00+00:00 [queued]>
[2023-08-02 00:00:01,209] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 00:00:01,209] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-08-02 00:00:01,209] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 00:00:01,227] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract> on 2023-08-01 00:00:00+00:00
[2023-08-02 00:00:01,236] {standard_task_runner.py:52} INFO - Started process 3539 to run task
[2023-08-02 00:00:01,241] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_api_marvel', 'extract', 'scheduled__2023-08-01T00:00:00+00:00', '--job-id', '1297', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_ok.py', '--cfg-path', '/tmp/tmpt02pn4nz', '--error-file', '/tmp/tmp3oxmn7ex']
[2023-08-02 00:00:01,242] {standard_task_runner.py:80} INFO - Job 1297: Subtask extract
[2023-08-02 00:00:01,349] {task_command.py:371} INFO - Running <TaskInstance: etl_api_marvel.extract scheduled__2023-08-01T00:00:00+00:00 [running]> on host 24cbf2f01ed0
[2023-08-02 00:00:01,568] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=arielmfeldman.af@gmail.com
AIRFLOW_CTX_DAG_OWNER=Ariel Feldman
AIRFLOW_CTX_DAG_ID=etl_api_marvel
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2023-08-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-01T00:00:00+00:00
[2023-08-02 00:00:02,774] {python.py:173} INFO - Done. Returned value was: None
[2023-08-02 00:00:02,797] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=etl_api_marvel, task_id=extract, execution_date=20230801T000000, start_date=20230802T000001, end_date=20230802T000002
[2023-08-02 00:00:02,823] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-02 00:00:02,858] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-08-02 00:00:06,194] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
