[2023-07-14 00:04:35,400] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_context.probando_context scheduled__2023-07-12T00:00:00+00:00 [queued]>
[2023-07-14 00:04:35,421] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_context.probando_context scheduled__2023-07-12T00:00:00+00:00 [queued]>
[2023-07-14 00:04:35,421] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-14 00:04:35,421] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-07-14 00:04:35,421] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-14 00:04:35,451] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): probando_context> on 2023-07-12 00:00:00+00:00
[2023-07-14 00:04:35,460] {standard_task_runner.py:52} INFO - Started process 1364 to run task
[2023-07-14 00:04:35,464] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_context', 'probando_context', 'scheduled__2023-07-12T00:00:00+00:00', '--job-id', '816', '--raw', '--subdir', 'DAGS_FOLDER/first_context.py', '--cfg-path', '/tmp/tmpjye1erk9', '--error-file', '/tmp/tmp65okd4j1']
[2023-07-14 00:04:35,465] {standard_task_runner.py:80} INFO - Job 816: Subtask probando_context
[2023-07-14 00:04:35,574] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_context.probando_context scheduled__2023-07-12T00:00:00+00:00 [running]> on host 7a1b6d75866e
[2023-07-14 00:04:35,726] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ariel Feldman
AIRFLOW_CTX_DAG_ID=mi_primer_context
AIRFLOW_CTX_TASK_ID=probando_context
AIRFLOW_CTX_EXECUTION_DATE=2023-07-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-12T00:00:00+00:00
[2023-07-14 00:04:35,728] {logging_mixin.py:115} INFO - {'conf': <***.configuration.AirflowConfigParser object at 0x7fde30f4a690>, 'dag': <DAG: mi_primer_context>, 'dag_run': <DagRun mi_primer_context @ 2023-07-12 00:00:00+00:00: scheduled__2023-07-12T00:00:00+00:00, externally triggered: False>, 'data_interval_end': DateTime(2023, 7, 13, 0, 0, 0, tzinfo=Timezone('UTC')), 'data_interval_start': DateTime(2023, 7, 12, 0, 0, 0, tzinfo=Timezone('UTC')), 'ds': '2023-07-12', 'ds_nodash': '20230712', 'execution_date': <Proxy at 0x7fde1c7f58c0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fde1c7a57a0>, 'execution_date', DateTime(2023, 7, 12, 0, 0, 0, tzinfo=Timezone('UTC')))>, 'inlets': [], 'logical_date': DateTime(2023, 7, 12, 0, 0, 0, tzinfo=Timezone('UTC')), 'macros': <module '***.macros' from '/home/***/.local/lib/python3.7/site-packages/***/macros/__init__.py'>, 'next_ds': <Proxy at 0x7fde1c7b88c0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fde1c7a57a0>, 'next_ds', '2023-07-13')>, 'next_ds_nodash': <Proxy at 0x7fde1c7b8910 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fde1c7a57a0>, 'next_ds_nodash', '20230713')>, 'next_execution_date': <Proxy at 0x7fde1c7b8960 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fde1c7a57a0>, 'next_execution_date', DateTime(2023, 7, 13, 0, 0, 0, tzinfo=Timezone('UTC')))>, 'outlets': [], 'params': {}, 'prev_data_interval_start_success': None, 'prev_data_interval_end_success': None, 'prev_ds': <Proxy at 0x7fde1c7b89b0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fde1c7a57a0>, 'prev_ds', '2023-07-11')>, 'prev_ds_nodash': <Proxy at 0x7fde1c7b8a00 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fde1c7a57a0>, 'prev_ds_nodash', '20230711')>, 'prev_execution_date': <Proxy at 0x7fde1c7b8a50 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fde1c7a57a0>, 'prev_execution_date', DateTime(2023, 7, 11, 0, 0, 0, tzinfo=Timezone('UTC')))>, 'prev_execution_date_success': <Proxy at 0x7fde1c7b8aa0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fde1c7a57a0>, 'prev_execution_date_success', None)>, 'prev_start_date_success': None, 'run_id': 'scheduled__2023-07-12T00:00:00+00:00', 'task': <Task(PythonOperator): probando_context>, 'task_instance': <TaskInstance: mi_primer_context.probando_context scheduled__2023-07-12T00:00:00+00:00 [running]>, 'task_instance_key_str': 'mi_primer_context__probando_context__20230712', 'test_mode': False, 'ti': <TaskInstance: mi_primer_context.probando_context scheduled__2023-07-12T00:00:00+00:00 [running]>, 'tomorrow_ds': <Proxy at 0x7fde1c7b8af0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fde1c7a57a0>, 'tomorrow_ds', '2023-07-13')>, 'tomorrow_ds_nodash': <Proxy at 0x7fde1c7b8b40 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fde1c7a57a0>, 'tomorrow_ds_nodash', '20230713')>, 'ts': '2023-07-12T00:00:00+00:00', 'ts_nodash': '20230712T000000', 'ts_nodash_with_tz': '20230712T000000+0000', 'var': {'json': None, 'value': None}, 'conn': None, 'yesterday_ds': <Proxy at 0x7fde1c7b8b90 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fde1c7a57a0>, 'yesterday_ds', '2023-07-11')>, 'yesterday_ds_nodash': <Proxy at 0x7fde1c7b8be0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fde1c7a57a0>, 'yesterday_ds_nodash', '20230711')>, 'templates_dict': None}
[2023-07-14 00:04:35,728] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/first_context.py", line 15, in _print_context
    end = context['nex_execution_date'],
KeyError: 'nex_execution_date'
[2023-07-14 00:04:35,743] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=mi_primer_context, task_id=probando_context, execution_date=20230712T000000, start_date=20230714T000435, end_date=20230714T000435
[2023-07-14 00:04:35,770] {standard_task_runner.py:97} ERROR - Failed to execute job 816 for task probando_context ('nex_execution_date'; 1364)
[2023-07-14 00:04:35,798] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-14 00:04:35,861] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
