[2023-07-13 21:08:07,706] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2022-09-29T00:00:00+00:00 [queued]>
[2023-07-13 21:08:07,942] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2022-09-29T00:00:00+00:00 [queued]>
[2023-07-13 21:08:07,944] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 21:08:07,944] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-07-13 21:08:07,944] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 21:08:08,011] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): segunda_tarea> on 2022-09-29 00:00:00+00:00
[2023-07-13 21:08:08,022] {standard_task_runner.py:52} INFO - Started process 1250 to run task
[2023-07-13 21:08:08,035] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'segunda_tarea', 'scheduled__2022-09-29T00:00:00+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmpa0l6su3f', '--error-file', '/tmp/tmp7usy2097']
[2023-07-13 21:08:08,035] {standard_task_runner.py:80} INFO - Job 187: Subtask segunda_tarea
[2023-07-13 21:08:09,193] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2022-09-29T00:00:00+00:00 [running]> on host 7a1b6d75866e
[2023-07-13 21:08:11,992] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ari Feldman
AIRFLOW_CTX_DAG_ID=mi_primer_dag_v3
AIRFLOW_CTX_TASK_ID=segunda_tarea
AIRFLOW_CTX_EXECUTION_DATE=2022-09-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-29T00:00:00+00:00
[2023-07-13 21:08:11,994] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-07-13 21:08:11,995] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hola, soy la tarea 2 y sere corrida luego de la Tarea 1']
[2023-07-13 21:08:12,531] {subprocess.py:85} INFO - Output:
[2023-07-13 21:08:12,550] {subprocess.py:92} INFO - hola, soy la tarea 2 y sere corrida luego de la Tarea 1
[2023-07-13 21:08:12,550] {subprocess.py:96} INFO - Command exited with return code 0
[2023-07-13 21:08:13,783] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=mi_primer_dag_v3, task_id=segunda_tarea, execution_date=20220929T000000, start_date=20230713T210807, end_date=20230713T210813
[2023-07-13 21:08:13,890] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-07-13 21:08:13,897] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 1250. PIDs of all processes in the group: [1250]
[2023-07-13 21:08:13,897] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 1250
[2023-07-13 21:08:13,998] {process_utils.py:75} INFO - Process psutil.Process(pid=1250, status='terminated', exitcode=0, started='21:08:07') (1250) terminated with exit code 0
